name: base
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - anaconda-anon-usage=0.4.4
  - appnope=0.1.4
  - archspec=0.2.3
  - arrow-cpp=16.1.0
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - conda=24.9.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=43.0.0
  - datasets=2.19.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.8
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - filelock=3.13.1
  - fmt=9.1.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libarchive=3.7.4
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libcxx=19.1.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - menuinst=2.1.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python.app=3
  - python_abi=3.12
  - pytorch=2.6.0.dev20241023
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.1
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.9.11
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - safetensors=0.4.5
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - sentence-transformers=3.2.1
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tokenizers=0.20.1
  - torchaudio=2.5.0.dev20241023
  - torchvision=0.20.0.dev20241023
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.45.2
  - truststore=0.8.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - attorney==2.0.0
      - blessed==1.20.0
      - blis==1.0.1
      - catalogue==2.0.10
      - click==8.1.7
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - cymem==2.0.8
      - dnspython==2.7.0
      - editor==1.6.6
      - email-validator==2.2.0
      - inquirer==3.4.0
      - langcodes==3.4.1
      - language-data==1.2.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - murmurhash==1.0.10
      - numpy==2.0.2
      - preshed==3.0.9
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - readchar==4.2.1
      - rich==13.9.4
      - runs==1.2.2
      - shellingham==1.5.4
      - smart-open==7.0.5
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.13.1
      - thinc==8.3.2
      - typer==0.13.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
      - xmod==1.8.1
